### ISSUE TITLE
Not an Issue but a feature request

### ISSUE THREAD

**Issue by Dethkiller15** [terrorist-squad/DockerChaturbateRecorderGUI#11]
Why not just have a static location inside the container for the files to download to like say "/code/Captures/" and then allow us to set it via linking folders/volumes with the container?

**Comment by Dethkiller15** [comment]
Also there is this github that does roughly the same thing as this one but it doesnt make a bunch of containers for each model. could you impliment the same stream capture method it uses?

https://github.com/superagentp/ChaturbateRecorder4Docker

**Comment by terrorist-squad** [comment]
i'll take a look and maybe implement an optional adapter

**Comment by terrorist-squad** [comment]
Hi Dethkiller15,
there is now an adapter that does not need any additional containers. Please test the following comose file:

```
version: '2'

services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui:2.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'ShellAdapter' #For Kubernetes 'KubernetesAdapter'
      CONTAINER_PREFFIX: 'cr_'
      USER_ID: 0
      USER_GID: 0
    volumes:
      - /Users/christianknedel/videos:/code/database
      - /Users/christianknedel/videos:/code/videos
    ports:
      - "8002:8000"
```
