### ISSUE TITLE
container prefix

### ISSUE THREAD

**Issue by mytrntsite** [terrorist-squad/DockerChaturbateRecorderGUI#38]
Is it possible that the container does not add a prefix before the filename ?

**Comment by ChristianKnedel** [comment]
You can change the attribute “CONTAINER_PREFFIX” in the docker-compose.yml, for example:

```
version: '2'

services:    
  app:
    image: chrisknedel/chaturbate-recorder-gui:3.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: “Europe/Berlin”
      ABSOLUTE_HOST_MEDIA: “/Users/christianknedel/videos/”
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or “0” to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or “0” to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter'
      CONTAINER_PREFFIX: ''
      RECORDER_IMAGE: 'chrisknedel/chaturbate-recorder:3.0'
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
    ports:
      - “8002:8000”

```
