### ISSUE TITLE
[Bug] - Database Locked when using smbshare path failure to create intial db

### ISSUE THREAD

**Issue by J0nDoe** [terrorist-squad/DockerChaturbateRecorderGUI#42]
For example if you include the following in your docker-compose

```yaml

volumes:
  recordings:
    driver: local
    driver_opts:
      type: cifs
      device: //network-path/Stuff/Recordings  # SMB path
      o: username=<username>,password=<password>,vers=3.0,uid=1000,gid=1000,dir_mode=0777,file_mode=0777
```

Even though the specified user name and password is correct and has the correct permissions, I can see the db.sqlite3 db file 

```
recorder_app  | Migrations for 'main':
recorder_app  |   apps/frontend/main/migrations/0001_initial.py
recorder_app  |     - Create model WishlistItem
recorder_app  | Traceback (most recent call last):
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 253, in _commit
recorder_app  | Operations to perform:
recorder_app  |   Apply all migrations: admin, auth, contenttypes, main, sessions
recorder_app  | Running migrations:
recorder_app  |     return self.connection.commit()
recorder_app  |            ^^^^^^^^^^^^^^^^^^^^^^^^
recorder_app  | sqlite3.OperationalError: database is locked
recorder_app  |
recorder_app  | The above exception was the direct cause of the following exception:
recorder_app  |
recorder_app  | Traceback (most recent call last):
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/migrations/recorder.py", line 67, in ensure_schema
recorder_app  |     with self.connection.schema_editor() as editor:
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/sqlite3/schema.py", line 36, in __exit__
recorder_app  |     super().__exit__(exc_type, exc_value, traceback)
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/schema.py", line 126, in __exit__
recorder_app  |     self.atomic.__exit__(exc_type, exc_value, traceback)
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/transaction.py", line 246, in __exit__
recorder_app  |     connection.commit()
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/utils/asyncio.py", line 25, in inner
recorder_app  |     return func(*args, **kwargs)
recorder_app  |            ^^^^^^^^^^^^^^^^^^^^^
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 277, in commit
recorder_app  |     self._commit()
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 252, in _commit
recorder_app  |     with self.wrap_database_errors:
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/utils.py", line 90, in __exit__
recorder_app  |     raise dj_exc_value.with_traceback(traceback) from exc_value
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 253, in _commit
recorder_app  |     return self.connection.commit()
recorder_app  |            ^^^^^^^^^^^^^^^^^^^^^^^^
recorder_app  | django.db.utils.OperationalError: database is locked
recorder_app  |
recorder_app  | During handling of the above exception, another exception occurred:
recorder_app  |
recorder_app  | Traceback (most recent call last):
recorder_app  |   File "/code/manage.py", line 22, in <module>
recorder_app  |     main()
recorder_app  |   File "/code/manage.py", line 18, in main
recorder_app  |     execute_from_command_line(sys.argv)
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
recorder_app  |     utility.execute()
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 419, in execute
recorder_app  |     self.fetch_command(subcommand).run_from_argv(self.argv)
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/base.py", line 373, in run_from_argv
recorder_app  |     self.execute(*args, **cmd_options)
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/base.py", line 417, in execute
recorder_app  |     output = self.handle(*args, **options)
recorder_app  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/base.py", line 90, in wrapped
recorder_app  |     res = handle_func(*args, **kwargs)
recorder_app  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/commands/migrate.py", line 253, in handle
recorder_app  |     post_migrate_state = executor.migrate(
recorder_app  |                          ^^^^^^^^^^^^^^^^^
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/migrations/executor.py", line 100, in migrate
recorder_app  |     self.recorder.ensure_schema()
recorder_app  |   File "/usr/local/lib/python3.12/dist-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
recorder_app  |     raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
recorder_app  | django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)
recorder_app  | -> compilemessages
recorder_app  | -> starte server
recorder_app  | Watching for file changes with StatReloader
``` 

```
# whoami
root
# id
uid=0(root) gid=0(root) groups=0(root)
#
```

**Comment by ChristianKnedel** [comment]
Please post the complete compose file. There is a uid and gid as environment 

version: '2'

services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui:3.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/christianknedel/videos/"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chatrubate-recorder:3.0'
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
    ports:
      - "8002:8000"

**Comment by J0nDoe** [comment]
This is my compose file, which looks identical, I did change the UID / GUID to make the the uid / guid of the volume mount the same to 1000 but it didn't result any anything different

```yaml
services:
  app:
    image: chrisknedel/chaturbate-recorder-gui
    container_name: recorder_app
    restart: always
    environment:
      TZ: "America/New_York"
      ABSOLUTE_HOST_MEDIA: "S:/Recordings" # SMB path
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: "DockerAdapter"
      CONTAINER_PREFFIX: "cr_"
      RECORDER_IMAGE: "chrisknedel/chaturbate-recorder"
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - recordings:/code/database
    ports:
      - "8002:8000"
volumes:
  recordings:
    driver: local
    driver_opts:
      type: cifs
      device: //network-path/Stuff/Recordings  # SMB path
      o: username=<username>,password=<password>,vers=3.0,uid=1000,gid=1000,dir_mode=0777,file_mode=0777
```

**Comment by J0nDoe** [comment]
Interestingly enough this seems to work 

```yaml
services:
  app:
    image: chrisknedel/chaturbate-recorder-gui:latest
    container_name: recorder_app
    restart: always
    environment:
      TZ: "America/New_York"
      ABSOLUTE_HOST_MEDIA: "S:/Recordings" # SMB path
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: "DockerAdapter"
      CONTAINER_PREFFIX: "cr_"
      RECORDER_IMAGE: "chrisknedel/chaturbate-recorder"
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - S:/Recordings:/code/database
    ports:
      - "8002:8000"
```
