### ISSUE TITLE
Recording stops at 1 GB

### ISSUE THREAD

**Issue by meddle99** [terrorist-squad/DockerChaturbateRecorderGUI#8]
no matter what I have set in the yml, recording stops at 1 gb.

i tried:
      LIMIT_MAXIMUM_FOLDER_GB: 2000 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOCKER_CONTAINER: 100 #or "0" to disable this limit

and i noticed the env variables did not match so i tried:
      MAXIMUM_FOLDER_GB: 2000 #or "0" to disable this limit
      MAXIMUM_DOCKER_CONTAINER: 100 #or "0" to disable this limit

but in the docker images for each channel, the settings seems to be ignored:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/30960194/161447618-bc1e4dd1-e22f-4a4a-b585-2cecbe32a4c4.png">

what am i doing wrong?

**Comment by terrorist-squad** [comment]
please check the latest images

```
$ docker pull chrisknedel/chatrubate-recorder
$ docker pull chrisknedel/chatrubate-recorder-gui
```

And started with this compose file:

```
version: '2'

services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/christianknedel/videos/"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOCKER_CONTAINER: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter' #For Kubernetes 'KubernetesAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chatrubate-recorder'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
    ports:
      - "8002:8000"

```


with
```
$ docker-compose -f stable.yml up -d
```
